spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://spots-app.eu.auth0.com/
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:jobFinderDB
  sql:
    init:
      platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create-drop

auth0:
  audience: 'http:localhost:8080'
