spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:jobFinderDB
  sql:
    init:
      platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create-drop
