openapi: 3.0.3
info:
  title: Open API Definitions for jiu jitsu job finder
  description: |-
  # termsOfService: http://swagger.io/terms/
  contact:
    email: evangelos.vatikiotis@outlook.com
  license:
    name: AGPL 
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: "3.0"

servers:
  - url: http://localhost:8080
tags:
  - name: jobs 
    description: Create and find for Jobs related to Jiu Jitsu
  
paths:
  /jobs:
    get:
      tags:
        - jobs
      summary: Get all jobs 
      description: Returns a single job
      operationId: getAll
    
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobArray'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Job not found
    put:
      tags:
        - jobs
      summary: Update an existing job
      description: Update an existing job by Id
      operationId: updateJob
      requestBody:
        description: Update an existent job in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Job'
          
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Job'
        '400':
          description: Invalid ID supplied
        '404':
          description: Job not found
        '405':
          description: Validation exception
    
    post:
      tags:
        - jobs
      summary: Create a new job 
      description: Create a new job
      operationId: createJob
      requestBody:
        description: Create a new job 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Job'
        
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Job'
        '405':
          description: Invalid input
     
  
  
  /jobs/{id}:
    get:
      tags:
        - jobs
      summary: Find job by ID
      description: Returns a single jobb
      operationId: findJobById
      parameters:
        - name: id
          in: path
          description: ID of job to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Job not found
  
 
components:
  schemas:
    
    Job:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          example: Jiu Jitsu instructor in Ukraine
        description:
          type: string
          example: John
        creator:
          type: string
          example: James
    
  
    
    JobArray:
      description: List of job object
      type: array
      items:
        $ref: '#/components/schemas/Job'
        
