openapi: 3.0.3
info:
  title: Open API Definitions for jiu jitsu job finder
  description: |-
  # termsOfService: http://swagger.io/terms/
  contact:
    email: evangelos.vatikiotis@outlook.com
  license:
    name: AGPL
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: "3.0"

servers:
  - url: http://localhost:8080/api
tags:
  - name: jobs
    description: Create and find for Jobs related to Jiu Jitsu

paths:
  /jobs:
    get:
      tags:
        - jobs
      summary: Get all jobs
      description: Returns a single job
      operationId: getAll

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobArray'
        '400':
          description: Invalid ID supplied
        '404':
          description: Job not found


    post:
      security:
        - bearerAuth: []
      tags:
        - jobs

      summary: Create a new job
      description: Create a new job
      operationId: createJob
      requestBody:
        description: Create a new job
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobDTO'

        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDTO'
            application/xml:
              schema:
                $ref: '#/components/schemas/JobDTO'
        '405':
          description: Invalid input



  /jobs/{id}:
    put:
      tags:
        - jobs
      security:
        - bearerAuth: []

      summary: Update an existing job
      description: Update an existing job by Id
      operationId: updateJob
      parameters:
        - name: id
          in: path
          description: ID of job to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update an existent job in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobDTO'

        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDTO'
            application/xml:
              schema:
                $ref: '#/components/schemas/JobDTO'
        '400':
          description: Invalid ID supplied
        '404':
          description: Job not found
        '405':
          description: Validation exception
    get:
      tags:
        - jobs
      summary: Find job by ID
      description: Returns a single jobb
      operationId: findJobById
      parameters:
        - name: id
          in: path
          description: ID of job to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDTO'
        '400':
          description: Invalid ID supplied
        '404':
          description: Job not found


components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    JobDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        creator:
          type: string
        title:
          type: string
          example: Jiu Jitsu instructor in Amsterdam
        paymentAmount:
          type: number
          description: Amount expressed as a decimal number of major currency units
          format: decimal
          example: 99.95
        currency:
          type: string
          format: iso-4217
          example: EUR
        paymentType:
          type: string
          enum: [MONTHLY, ONE_TIME, OTHER]
        description:
          type: string
          example: Our martial arts studio is seeking a Jiu Jitsu Instructor to join our team. The successful candidate will be responsible for
        startingDate:
          type: string
          format: date
        endingDate:
          type: string
          format: date

    
    JobArray:
      description: List of job object
      type: array
      items:
        $ref: '#/components/schemas/JobDTO'
        
